# from list data

In [1]:
import torch
import numpy as np

list_data = [ [10, 20], [30, 40] ]
tensor1 = torch.Tensor(list_data) # python list로 부터 직접 tensor를 만들 수 있다

print(tensor1)
# 속성(type), 모양(shape)
print(f'tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}')
# 자료형(dtype), 저장되는 위치(device)
print(f'tensor dtype: {tensor1.dtype}, tensor.device: {tensor1.device}')

# https://hyunhp.tistory.com/740
if torch.cuda.is_available():  # GPU를 이용할 수 있다면
  tensor1 = tensor1.to('cuda') # tensor를 GPU로 이동

print(f'tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}')
print(f'tensor dtype: {tensor1.dtype}, tensor.device: {tensor1.device}')

tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor.device: cpu
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor.device: cpu


# from Numpy

In [ ]:
numpy_data = np.array(list_data)

tensor2_1 = torch.from_numpy(numpy_data) # numpy data로 부터 tensor 생성

print(tensor2_1)
print(f'tensor type: {type(tensor2_1)}, tensor shape: {tensor2_1.shape}')     # 속성(type), 모양(shape)
print(f'tensor dtype: {tensor2_1.dtype}, tensor.device: {tensor2_1.device}')  # 자료형(dtype), 저장되는 위치(device)

# numpy로 부터 만들어진 tensor는 기본적으로 int type
# DeepLearning의 기본 data type은 float 이므로
# float()으로 type casting해 주는 것이 필요함
tensor2_2 = torch.from_numpy(numpy_data).float()

print(tensor2_2)
print(f'tensor type: {type(tensor2_2)}, tensor shape: {tensor2_2.shape}')     # 속성(type), 모양(shape)
print(f'tensor dtype: {tensor2_2.dtype}, tensor.device: {tensor2_2.device}')  # 자료형(dtype), 저장되는 위치(device)

tensor([[10, 20],
        [30, 40]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.int64, tensor.device: cpu
tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor.device: cpu


# to Numpy

In [ ]:
# 0~1 사이의 균일한 분포의 random 값을 생성
tensor3 = torch.rand(2, 2)
print('tensor3 ==========================')
print(tensor3)

# 평균이 0, 분산이 1인 정규분포를 갖는 random 값을 생성
# DeepLearning에서 Weight와 Bias를 초기화할 경우 많이 사용
tensor4 = torch.randn(2, 2)
print('tensor4 ==========================')
print(tensor4)

tensor5 = torch.randn(2, 2)
print('tensor5 ==========================')
print(tensor5)

numpy_from_tensor = tensor5.numpy() # Numpy data 로 변환
print('numpy_from_tensor ==========================')
print(f'type: {type(numpy_from_tensor)}')
print(numpy_from_tensor)

tensor3 ==========================
tensor([[0.8041, 0.2874],
        [0.0836, 0.8908]])
tensor4 ==========================
tensor([[-0.2460,  0.7619],
        [ 0.7623, -1.0843]])
tensor5 ==========================
tensor([[-0.7178, -0.4029],
        [ 1.0751,  1.3422]])
numpy_from_tensor ==========================
type: <class 'numpy.ndarray'>
[[-0.7177871  -0.40288544]
 [ 1.0750556   1.3422432 ]]


# indexing/slicing

In [ ]:
tensor6 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
tensor7 = torch.Tensor([[7, 8, 9], [10, 11, 12]])

# tensor6의 첫번째 행의 모든 data
print(tensor6[0, :])
print(tensor6[0])
# tensor6의 모든 행의 data와 두번째 열 이후의 data의 교집합
print(tensor6[:, 1:])
# tensor7의 첫번째 행부터 두번째 행까지의 data와 첫번째 열에서 두번째 열 까지 data의 교집합
print(tensor7[:2, :2])
# tensor7의 두번째 행의 모든 data와 마지막 열의 모든 data의 교집합
print(tensor7[1, -1])
# tensor7의 모든 data와 두번째 열의 모든 data와의 교집합
print(tensor7[:, 1])
print(tensor7[..., 1])  # ... : 모든 을 의미

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([[2., 3.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [10., 11.]])
tensor(12.)
tensor([ 8., 11.])
tensor([ 8., 11.])


# 원소 간 곱(Element-wise Product)

In [ ]:
# 크기가 같은 tensor에서, 동일한 위치에 있는 element끼리 곱한다.
print(f'tensor6: \n{tensor6}')
print(f'tensor7: \n{tensor7}')
tensor8 = tensor6.mul(tensor7) # matrix X matrix, broadcasting 안 됨
print(f'tensor8: \n{tensor8}')
tensor8 = tensor6.add(tensor7)
print(f'tensor8: \n{tensor8}')

tensor6: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor7: 
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor8: 
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])
tensor9: 
tensor([[ 58.,  64.],
        [139., 154.]])


# 행렬 곱(Matrix Multiplication)

In [ ]:
# Matrix Multiplication은 앞 matrix의 col 수와 뒤 matrix row 수가 같아야 가능하다
# 여기서는 2개 모두 2x3 이므로 error 발생
# broadcasting 안 됨
tensor9 = tensor6.matmul(tensor7)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
tensor9 = tensor6.matmul(tensor7.view(3, 2)) # view() 는 reshape()과 거의 동일한 기능
print(tensor9)

tensor([[ 58.,  64.],
        [139., 154.]])


# concatenate

In [ ]:
print('tensor6 ==========================')
print(tensor6)
print('tensor7 ==========================')
print(tensor7)

# col 기준으로, 즉, 세로로 합치라는 의미
tensor_cat = torch.cat([tensor6, tensor7])
print('tensor_cat ==========================')
print(tensor_cat)

# dim=0 : col 기준으로, 즉, 세로로 합치라는 의미, default
tensor_cat_dim0 = torch.cat([tensor6, tensor7], dim=0)
print('tensor_cat_dim0 ==========================')
print(tensor_cat_dim0)

# dim=1 : row 기준으로, 즉, 가로로 합치라는 의미
tensor_cat_dim1 = torch.cat([tensor6, tensor7], dim=1)
print('tensor_cat_dim1 ==========================')
print(tensor_cat_dim1)

tensor6 ==========================
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor7 ==========================
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor_cat ==========================
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor_cat_dim0 ==========================
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor_cat_dim1 ==========================
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])
